@startuml

component "Central" as Central

component "xDuinoRail" as Decoder#Salmon

Decoder <- Central : MM / DCC
Central <- Decoder : mfx / RailCom / RailComPlus


component "MCU base boards" as MCU {

component ATMEGA328
component RP2040
component SAMD21
component STM32
component "RISC-V"

}
Decoder <--> MCU : "Arduino Headers (D2/D3/VIN)\nXIAO pinout"

component "Sensors & Actors" as SENS {

component "Motor Driver"
component "Servo Driver"
component "LED Driver"
component "Sensors"

}
SENS <--> Decoder : "Arduino Headers\nXIAO pinout"

@enduml
